mysql:
  image: mysql:5.7
  ports:
    - '${HOST_PP}3306:3306'
  restart: always
  environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
redis:
  image: redis
  ports:
    - '${HOST_PP}6379:6379'